### ISSUE TITLE
If the cat runs under https the webservice connection fails

### ISSUE THREAD

**Issue by mottolini** [cheshire-cat-ai/api-client-ts#46]
The problem lies in the fact that using a baseUrl starting with `https` generates a wrong targetUrl:
 
<img width="632" alt="Screenshot 2024-10-04 at 07 34 05" src="https://github.com/user-attachments/assets/3ab3ae47-7c74-49cb-b61e-a197e7046f67">

Originally discovered using [widget-CCAT-react](https://github.com/AndreaPesce2002/widget-CCAT-react): https://github.com/AndreaPesce2002/widget-CCAT-react/issues/1

**Comment by zAlweNy26** [comment]
You should not pass the protocol to the `baseUrl` property. If you want to enable https, you must set `secure` to true.

**Comment by pieroit** [comment]
> You should not pass the protocol to the `baseUrl` property. If you want to enable https, you must set `secure` to true.

I guess `baseUrl` should be named `host` because the URL contains the protocol 
https://en.wikipedia.org/wiki/URL

**Comment by zAlweNy26** [comment]
Fixed in v0.11.1
